name: QuesGenie-CD

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: 9.0.x
      - name: restore dependenceis
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c release
      - name: publish
        run: dotnet publish ./QuesGenie.API/QuesGenie.API.csproj -o ${{ env.DOTNET_ROOT }}/api --no-build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: api-artifact
          path: ${{env.DOTNET_ROOT}}/api
  deploy-prod:
    environment: 
      name: 'Production'
      url: 'https://quesgenie.azurewebsites.net'
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Download a Build Artifact
       uses: actions/download-artifact@v4.1.8
       with:
          name: api-artifact
     - name: Azure WebApp
       uses: Azure/webapps-deploy@v3.0.1
       with:
        app-name: quesgenie
        publish-profile: ${{ secrets.QUES_GENIE_PUBLISH_PROFILE_PROD }} 
